# Generated by Django 4.2.4 on 2023-09-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_courses_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookies', to='application.author'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_average_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
