# Generated by Django 4.2.4 on 2023-09-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(to='application.courses'),
        ),
    ]
