# Generated by Django 4.2.4 on 2023-09-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_students_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date_of_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date_of_the_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
