# Generated by Django 4.2.4 on 2023-09-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_courses_date_of_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='application.author'),
        ),
    ]
